version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: movieflix-postgres
    environment:
      POSTGRES_DB: movieflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
        - "5432:5432"
    restart: always